stages:
  load_data:
    cmd: python src/load_data.py --config=config/params.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - data_given/data.csv
    outs:
      - data/raw/train.csv
      
  preprocess_data:
    cmd: python src/preprocess.py --config=config/params.yaml 
    deps:
      - src/categorical_encoding.py
      - src/numerical_scaling.py
      - src/preprocess.py
      - data/raw/train.csv
    outs:
      - data/interim/interim_data.csv


  split_data:
    cmd: python src/split_data.py --config=config/params.yaml
    deps:
      - src/split_data.py
      - data/interim/interim_data.csv
    outs:
      - data/processed/train_data.csv      
      - data/processed/test_data.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=config/params.yaml
    deps:
    - data/processed/train_data.csv
    - data/processed/test_data.csv
    - src/train_and_evaluate.py
    - reports/params.json
    - reports/scores.json
    
      
#    metrics:
#    - reports/scores.json:
#        cache: false
#    - reports/params.json:
#        cache: false
    outs:
    - saved_models/model.joblib
