base:
  project: adult census income prediction
  random_state: 42
# name of the y variable i.e. target column
  target_col: Output

data_source:
  s3_source: data_given/data.csv

load_data:
  raw_dataset_csv: data/raw/train.csv

transformers:
  base_n_encoder: transformers/baseN_encoder.pkl
  standard_scaler: transformers/standard_scaler.pkl

data_preprocessing:
  preprocessed_data_dir: data/processed/data.csv
 


split_data:
  train_path: data/processed/train_data.csv 
  test_path: data/processed/test_data.csv
  test_size: 0.2



#train_data_preparation:
#  schema_training: config/schema_training.json
#  good_validated_raw_dir: data/Training_Raw_files_validated/Good_raw
# bad_validated_raw_dir: data/Training_Raw_files_validated/Bad_raw
#  TrainingArchiveBadData: data/TrainingArchiveBadData
#  Training_FileFromDB: data/Training_FileFromDB
#  master_csv: master.csv

#pred_data_preparation:
#  prediction_db: Prediction.db
# prediction_db_dir: Prediction_Database
 # schema_prediction: config/schema_prediction.json
 # good_validated_raw_dir: data/Prediction_Raw_files_validated/Good_raw
 # bad_validated_raw_dir: data/Prediction_Raw_files_validated/Bad_raw
  #PredictionArchiveBadData: data/PredictionArchiveBadData
  #Prediction_FileFromDB: data/Prediction_FileFromDB
  #master_csv: master.csv
  #Prediction_Output_File: Prediction_Output_File/Predictions.csv



saved_models:
  model_dir: models

reports:
  params: reports/params.json
  scores: reports/scores.json

data_preprocessing:
  preprocessed_data_dir: data/preprocessed_data
  preprocessed_data_dir_pred: data/preprocessed_data_pred


#  KNNImputer: 
#    n_neighbors: 3 
#    weights: uniform
#    missing_values: nan

#  KMeansClustering:
#    init: k-means++
#    n_cluster_max: 11
#    KneeLocator: 
#      curve: convex
#      direction: decreasing
    

#artifacts_dir: 
#  general: general
#  mlflow: mlflow_artifacts


training:
  SVC:
    C: 1
    kernel: rbf
    degree: 3
    gamma: scale
    tol: 0.001
    break_ties: True

#  random_forest:
#    cv: 5
#    verbose: 3
#    param_grid:
#      n_estimators: 
#        - 10
#        - 50
#        - 100
#        - 130 
#      criterion: 
#        - gini
#        - entropy
#      max_depth: 
#        - 2
#        - 4
#      max_features: 
#        - auto
#        - log2
#  xg_boost:
#    cv: 5
#    verbose: 3
#    param_grid:
#      learning_rate: 
#        - 0.5
#        - 0.1
#        - 0.01
#        - 0.001
#      max_depth: 
#        - 3
#        - 5
#        - 10
#        - 20
#      n_estimators: 
#        - 10
#        - 50
#        - 100
#        - 200
