base:
  project: adult census income prediction
  random_state: 42
# name of the y variable i.e. target column
  target_col: Output

data_source:
  s3_source: data_given/data.csv

load_data:
  raw_dataset_csv: data/raw/train.csv

transformers:
  base_n_encoder: transformers/baseN_encoder.pkl
  standard_scaler: transformers/standard_scaler.pkl

preprocess:
  preprocess_data_dir:  data/interim/interim_data.csv
 


split_data:
  train_path: data/processed/train_data.csv 
  test_path: data/processed/test_data.csv
  test_size: 0.2


model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

data_preprocessing:
  preprocessed_data_dir: data/preprocessed_data
  preprocessed_data_dir_pred: data/preprocessed_data_pred


estimators:
  SVC:
    params:
      C: 2
      kernel: rbf
      degree: 3
      gamma: scale
      tol: 0.001
    
webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticNetWineModel
  remote_server_uri: http://0.0.0.0:1234
